export const ADD_RECIPIE = 'ADD_RECIPIE';
export const EDIT_RECIPIE = 'EDIT_RECIPIE';
export const REMOVE_RECIPIE = 'REMOVE_RECIPIE';
export const SET_RECIPIES = 'SET_RECIPIES';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const SET_LOADING = 'SET_LOADING';